"""empty message

Revision ID: 1d54a7257ce0
Revises: 
Create Date: 2019-06-23 11:51:18.130333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d54a7257ce0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除标志，记录删除时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=250), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('email', name=op.f('uq_accounts_email'))
    )
    op.create_table('article_categories',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除标志，记录删除时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='文章分类ID'),
    sa.Column('name', sa.String(length=19), nullable=True, comment='文章分类名称'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_categories'))
    )
    op.create_table('articles',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除标志，记录删除时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='发布者账号ID'),
    sa.Column('title', sa.String(length=99), nullable=True, comment='文章标题'),
    sa.Column('summary', sa.Text(), nullable=True, comment='文章概要'),
    sa.Column('content_type', sa.Integer(), nullable=True, comment='文章编辑内容类型，1-Markdown，2-富文本'),
    sa.Column('content', sa.Text(), nullable=True, comment='文章主体内容'),
    sa.Column('content_markdown', sa.Text(), nullable=True, comment='Markdown 文本内容，当 content_type=1 时存在'),
    sa.Column('word_count', sa.Integer(), nullable=True, comment='文章字数'),
    sa.Column('read', sa.Integer(), nullable=True, comment='阅读次数'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='所属分类。0-未分类'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('status', sa.Integer(), nullable=True, comment='文章状态。1-已发布，2-未发布，3-已撤回'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles'))
    )
    op.create_table('operations',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除标志，记录删除时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='操作记录ID'),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='操作者账号ID'),
    sa.Column('account_name', sa.String(length=9), nullable=True, comment='操作者姓名'),
    sa.Column('summary', sa.String(length=19), nullable=True, comment='操作概要'),
    sa.Column('description', sa.String(length=99), nullable=True, comment='操作具体描述'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations'))
    )
    op.create_table('visits',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除标志，记录删除时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='访问记录ID'),
    sa.Column('ip', sa.String(length=19), nullable=True, comment='访问者ip地址'),
    sa.Column('page_url', sa.String(length=19), nullable=True, comment='访问页面地址'),
    sa.Column('page_type', sa.Integer(), nullable=True, comment='访问页面类型'),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='访问文章ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visits'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_table('operations')
    op.drop_table('articles')
    op.drop_table('article_categories')
    op.drop_table('accounts')
    # ### end Alembic commands ###
