"""empty message

Revision ID: 7a78c6a89ee6
Revises: 1d54a7257ce0
Create Date: 2019-06-23 11:51:45.830554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a78c6a89ee6'
down_revision = '1d54a7257ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=39), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_articles_uuid'), ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_articles_uuid'), type_='unique')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
