"""empty message

Revision ID: 9e02ab62a0a2
Revises: 7a78c6a89ee6
Create Date: 2019-06-30 00:23:01.677114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e02ab62a0a2'
down_revision = '7a78c6a89ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    site_config_table = op.create_table('site_config',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除标志，记录删除时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='配置ID'),
    sa.Column('title', sa.String(length=99), nullable=True, comment='站点标题'),
    sa.Column('subtitle', sa.String(length=99), nullable=True, comment='站点二级标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='站点描述'),
    sa.Column('page_size', sa.Integer(), nullable=True, comment='每页显示数据量'),
    sa.Column('friends', sa.JSON(), nullable=True, comment='友链'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_config'))
    )

    # Insert config data.
    op.bulk_insert(site_config_table, [
        {
            'title'      : 'LingKBlog',
            'subtitle'   : '欢迎来到 LingKBlog',
            'description': '博客 | LingKblog | 写作 | Markdown',
            'page_size'  : 10
        }
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_config')
    # ### end Alembic commands ###
